=== 404Mate/jext-reborn/community-packs/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"descriptionAsTooltip": {
			"type": "boolean"
		},
		"icon": {
			"type": "string",
			"format": "uri"
		},
		"authors": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"downloads": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"url": {
						"type": "string",
						"format": "uri"
					},
					"overrideName": {
						"type": "string"
					},
					"overrideAuthor": {
						"type": "string"
					},
					"overrideDescription": {
						"type": "string"
					},
					"baseIcon": {
						"type": "string",
						"format": "uri"
					}
				},
				"required": ["url"]
			}
		}
	},
	"required": ["name", "description", "descriptionAsTooltip", "icon", "authors", "downloads"]
}

=== 404Mate/jext-reborn/community-packs/minecraft_trails_and_tales.json
{
    "$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
    "name": "Minecraft: Trails & Tales",
    "description": "Soundtrack capturing the essence of Minecraft's new biomes and features.",
    "descriptionAsTooltip": false,
    "icon": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a0/99/73/a0997358-8e45-8102-140c-f3dd4691b77d/196922443176_Cover.jpg/1200x1200bf-60.jpg",
    "authors": ["Aaron Cherof"], 
    "downloads": [
        {
            "url": "https://youtu.be/Uu3dshFseaU",
            "overrideName": "Echo in the Wind",
            "overrideAuthor": "Aaron Cherof",
            "overrideDescription": "§6Trails & Tales captures the essence of Minecraft's new biomes and features with a collection of music tracks composed by Aaron Cherof.\n§2§o1st disc out of 4.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a0/99/73/a0997358-8e45-8102-140c-f3dd4691b77d/196922443176_Cover.jpg/1200x1200bf-60.jpg"
        },
        {
            "url": "https://youtu.be/ec9dLqGOcg0",
            "overrideName": "A Familiar Room",
            "overrideAuthor": "Aaron Cherof",
            "overrideDescription": "§6Trails & Tales captures the essence of Minecraft's new biomes and features with a collection of music tracks composed by Aaron Cherof.\n§2§o2nd disc out of 4.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a0/99/73/a0997358-8e45-8102-140c-f3dd4691b77d/196922443176_Cover.jpg/1200x1200bf-60.jpg"
        },
        {
            "url": "https://youtu.be/TaXlw0OmSOg",
            "overrideName": "Bromeliad",
            "overrideAuthor": "Aaron Cherof",
            "overrideDescription": "§6Trails & Tales captures the essence of Minecraft's new biomes and features with a collection of music tracks composed by Aaron Cherof.\n§2§o3rd disc out of 4.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a0/99/73/a0997358-8e45-8102-140c-f3dd4691b77d/196922443176_Cover.jpg/1200x1200bf-60.jpg"
        },
        {
            "url": "https://youtu.be/_lxjp54MMBg",
            "overrideName": "Crescent Dunes",
            "overrideAuthor": "Aaron Cherof",
            "overrideDescription": "§6Trails & Tales captures the essence of Minecraft's new biomes and features with a collection of music tracks composed by Aaron Cherof.\n§2§o4th disc out of 4.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a0/99/73/a0997358-8e45-8102-140c-f3dd4691b77d/196922443176_Cover.jpg/1200x1200bf-60.jpg"
        }
    ]
}

=== 404Mate/jext-reborn/community-packs/minecraft_nether_update.json
{
    "$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
    "name": "Minecraft: Nether Update",
    "description": "Ambient and atmospheric tracks capturing the eerie essence of the Nether dimension.",
    "descriptionAsTooltip": false,
    "icon": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e5/72/cc/e572cc72-ff09-4918-8599-7134ddf8e97e/192641512063_Cover.jpg/1200x1200bb.jpg",
    "authors": ["Lena Raine"], 
    "downloads": [
        {
            "url": "https://youtu.be/qHDuedbZYbc",
            "overrideName": "Chrysopoeia",
            "overrideAuthor": "Lena Raine",
            "overrideDescription": "§6The Nether Update soundtrack features a collection of ambient and atmospheric music tracks composed by Lena Raine, capturing the eerie and mysterious essence of the Nether dimension in Minecraft.\n§2§o1st disc out of 3.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e5/72/cc/e572cc72-ff09-4918-8599-7134ddf8e97e/192641512063_Cover.jpg/1200x1200bb.jpg"
        },
        {
            "url": "https://youtu.be/HcvKHX6kK6M",
            "overrideName": "Rubedo",
            "overrideAuthor": "Lena Raine",
            "overrideDescription": "§6The Nether Update soundtrack features a collection of ambient and atmospheric music tracks composed by Lena Raine, capturing the eerie and mysterious essence of the Nether dimension in Minecraft.\n§2§o2nd disc out of 3.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e5/72/cc/e572cc72-ff09-4918-8599-7134ddf8e97e/192641512063_Cover.jpg/1200x1200bb.jpg"
        },
        {
            "url": "https://youtu.be/32jUaAgflXc",
            "overrideName": "So Below",
            "overrideAuthor": "Lena Raine",
            "overrideDescription": "§6The Nether Update soundtrack features a collection of ambient and atmospheric music tracks composed by Lena Raine, capturing the eerie and mysterious essence of the Nether dimension in Minecraft.\n§2§o3rd disc out of 3.",
            "baseIcon": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e5/72/cc/e572cc72-ff09-4918-8599-7134ddf8e97e/192641512063_Cover.jpg/1200x1200bb.jpg"
        }
    ]
}

=== 404Mate/jext-reborn/community-packs/minecraft_tricky_trials.json
{
	"$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
	"name": "Minecraft: Tricky Trials",
	"description": "A collection of tracks capturing the essence of the new Trial Chambers.",
	"descriptionAsTooltip": false,
	"icon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg",
	"authors": ["Aaron Cherof", "Kumi Tanioka", "Lena Raine"],
	"downloads": [
		{
			"url": "https://youtu.be/SLS9tUa2GXI",
			"overrideName": "Featherfall",
			"overrideAuthor": "Aaron Cherof",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o1st disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/CcAV71mXg_8",
			"overrideName": "Watcher",
			"overrideAuthor": "Aaron Cherof",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o2nd disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/ray1Svv6Sl8",
			"overrideName": "Puzzlebox",
			"overrideAuthor": "Aaron Cherof",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o3rd disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/Y9menjGA86s",
			"overrideName": "Komorebi",
			"overrideAuthor": "Kumi Tanioka",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o4th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/8ravZ03m55A",
			"overrideName": "Pokopoko",
			"overrideAuthor": "Kumi Tanioka",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o5th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/Vaak5b8RRaY",
			"overrideName": "Yakusoku",
			"overrideAuthor": "Kumi Tanioka",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o6th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/6B7PqW2NKeQ",
			"overrideName": "Deeper",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o7th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/G49EncT1T14",
			"overrideName": "Eld Unknown",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o8th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		},
		{
			"url": "https://youtu.be/TRY0tH78Tjk",
			"overrideName": "Endless",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6A collection of tracks capturing the essence of the new Trial Chambers.\n§2§o9th disc out of 9.",
			"baseIcon": "https://cdn-images.dzcdn.net/images/cover/821c84c70c502f1bdd11d79a6ab2b83d/0x1900-000000-80-0-0.jpg"
		}
	]
}

=== 404Mate/jext-reborn/community-packs/minecraft_the_wild_update.json
{
	"$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
	"name": "Minecraft: The Wild Update",
	"description": "A serene and adventurous soundtrack for Minecraft's The Wild Update.",
	"descriptionAsTooltip": false,
	"icon": "https://i.scdn.co/image/ab67616d0000b2731e96072f9313fa912b7ffbd3",
	"authors": ["Lena Raine"],
	"downloads": [
		{
			"url": "https://youtu.be/DoUW5ZkblTs",
			"overrideName": "Firebugs",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6The Wild Update soundtrack features a serene and adventurous collection of music tracks composed by Lena Raine, capturing the essence of the new biomes and features in Minecraft's The Wild Update.\n§2§o1st disc out of 3.",
			"baseIcon": "https://i.scdn.co/image/ab67616d0000b2731e96072f9313fa912b7ffbd3"
		},
		{
			"url": "https://youtu.be/FMJoOTOBcwE",
			"overrideName": "Aerie",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6The Wild Update soundtrack features a serene and adventurous collection of music tracks composed by Lena Raine, capturing the essence of the new biomes and features in Minecraft's The Wild Update.\n§2§o2nd disc out of 3.",
			"baseIcon": "https://i.scdn.co/image/ab67616d0000b2731e96072f9313fa912b7ffbd3"
		},
		{
			"url": "https://youtu.be/daVhxk1Yx20",
			"overrideName": "Labyrinthine",
			"overrideAuthor": "Lena Raine",
			"overrideDescription": "§6The Wild Update soundtrack features a serene and adventurous collection of music tracks composed by Lena Raine, capturing the essence of the new biomes and features in Minecraft's The Wild Update.\n§2§o3rd disc out of 3.",
			"baseIcon": "https://i.scdn.co/image/ab67616d0000b2731e96072f9313fa912b7ffbd3"
		}
	]
}

=== 404Mate/jext-reborn/community-packs/minecraft_volume_alpha.json
{
    "$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
    "name": "Minecraft: Volume Alpha",
    "description": "This is the official, first and most popular Minecraft soundtrack.",
    "descriptionAsTooltip": false,
    "icon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg",
    "authors": ["C418"], 
    "downloads": [
        {
            "url": "https://youtu.be/6wv84OUmnwg",
            "overrideName": "Key",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o1st disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/Wv9P6hnNKIo",
            "overrideName": "Door",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o2nd disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/o3_InDEtpLA",
            "overrideName": "Subwoofer Lullaby",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o3rd disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/gGHU9TSUdVQ",
            "overrideName": "Death",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o4th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/aQKGqzjno2g",
            "overrideName": "Living Mice",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o5th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/Wu-hE0InpLw",
            "overrideName": "Moog City",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o6th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/D09Okc11afI",
            "overrideName": "Haggstrom",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o7th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/vxmOcAde_0s",
            "overrideName": "Minecraft",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o8th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/m7OqQkkm2P0",
            "overrideName": "Oxygene",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o9th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/LRQuwCBIoCs",
            "overrideName": "Equinoxe",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o10th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/KdOD0fZs_XU",
            "overrideName": "Mice on Venus",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o11th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/-R-Vl4GzYWY",
            "overrideName": "Dry Hands",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o12th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/sgrs4l9BqD8",
            "overrideName": "Wet Hands",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o13th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/RawVEMRBW8M",
            "overrideName": "Clark",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o14th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/yGj4a9ZtFeA",
            "overrideName": "Chris",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o15th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/dx_rYqJ5hNQ",
            "overrideName": "Excuse",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o16th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/xIQrC4CerB8",
            "overrideName": "Sweden",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o17th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/p02Ww4YrsiM",
            "overrideName": "Dog",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o18th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/WfLOBeeLtuE",
            "overrideName": "Danny",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o19th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/jbLfMAxwOc8",
            "overrideName": "Beginning",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o20th disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/s3kvkDGAjbQ",
            "overrideName": "Droopy Likes Ricochet",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o21st disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        },
        {
            "url": "https://youtu.be/Hm51fAadWUI",
            "overrideName": "Droopy Likes Your Face",
            "overrideAuthor": "C418",
            "overrideDescription": "§6This is the official, first and most popular Minecraft soundtrack.\n§2§o22nd disc out of 22.",
            "baseIcon": "https://c418.org/wp-content/uploads/2016/05/a3390257927_10.jpg"
        }
    ]
}

=== 404Mate/jext-reborn/community-packs/minecraft_volume_beta.json
{
	"$schema": "https://raw.githubusercontent.com/spartacus04/jext-reborn/refs/heads/gh-pages/community-packs/schema.json",
	"name": "Minecraft: Volume Beta",
	"description": "The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.",
	"descriptionAsTooltip": false,
	"icon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg",
	"authors": ["C418"],
	"downloads": [
		{
			"url": "https://youtu.be/0y53iF8BTSU",
			"overrideName": "Ki",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o1st disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/xLfm2nnCOpc",
			"overrideName": "Alpha",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o2nd disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/wGQDJNksrAM",
			"overrideName": "Dead Voxel",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o3rd disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/77Fv8gtZyuA",
			"overrideName": "Blind Spots",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o4th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/yuySSmW5cfo",
			"overrideName": "Flake",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o5th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/C8df2pbOX6g",
			"overrideName": "Moog City 2",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o6th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/DwXtbA64lHE",
			"overrideName": "Concrete Halls",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o7th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/8sglGXAfHLc",
			"overrideName": "Biome Fest",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o8th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/5ChvaSe6aK0",
			"overrideName": "Mutation",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o9th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/ao8U6D_F3dE",
			"overrideName": "Haunt Muskie",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o10th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/tMjk9wgrPAc",
			"overrideName": "Warmth",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o11th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/j1Z_Ihkluek",
			"overrideName": "Floating Trees",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o12th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/atgjKEgSqSU",
			"overrideName": "Aria Math",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o13th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/FVNSvz-UyuA",
			"overrideName": "Kyoto",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o14th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/8VY2RUyY0t4",
			"overrideName": "Ballad of the Cats",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o15th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/Mj6jF7I2s10",
			"overrideName": "Taswell",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o16th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/2vRBjHY7ReE",
			"overrideName": "Beginning 2",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o17th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/rbIGUF9QmXg",
			"overrideName": "Dreiton",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o18th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/-6mBUPdTmeI",
			"overrideName": "The End",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o19th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		},
		{
			"url": "https://youtu.be/tC_lJyeGxoA",
			"overrideName": "Intro",
			"overrideAuthor": "C418",
			"overrideDescription": "§6The sequel to Volume Alpha. It’s bigger, more varied and sometimes even dark and introspective.\n§2§o20th disc out of 20.",
			"baseIcon": "https://c418.org/wp-content/uploads/2016/05/a1112985681_10.jpg"
		}
	]
}
